from typing import Callable

def greet() -> str: ...

class Application:
    def on_update(self) -> None: ...
    def run(self) -> None: ...
    def should_close(self, close: bool) -> None: ...

def launch(create_app: Callable[[], Application]) -> Application: ...
